config/routes.rb
Rails.application.routes.draw do
  root "equipments#index"
  get "operationhistories/index"
  get "/lendings_history/index", to: "lendings_history#index"
  get "/lendings", to: "lendings#index"
  post "/lendings/:id", to: "lendings#lending"
  patch "/lendings/:id", to: "lendings#return"

  resources :equipments

  resources :operation_histories
  devise_for :users, controllers: {
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_one :lending, dependent: :nullify
  belongs_to :user, optional: true
  validates :genre, presence: true
  validates :lab_equipment_name, presence: true
  validates :maker_name, presence: true
  validates :product_name, presence: true
  validates :purchase_year, presence: true

  enum genre: {
    pc: 0,
    note_pc: 1,
    tera: 2,
    camera: 3,
    experiment: 4,
    others: 5,
  }
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  require 'csv'

  PER_PAGE = 20

  def index
    @q = Equipment.ransack(params[:q])
    @equipments = @q.result.page(params[:page]).per(PER_PAGE).order("#{sort_column} #{sort_direction}")
    @equipment = Equipment.new
    @equipments_csv = Equipment.all
    respond_to do |format|
      format.html
      format.csv do |csv|
      send_equipments_csv(@equipments_csv)
      end
    end

  end

  def create
    current_user.equipments.create!(equipment_params)
    lab_equipment_name = equipment_params[:lab_equipment_name]
    OperationHistory.create_log(current_user.id, lab_equipment_name, 0)
    redirect_to root_path
  end
  
  def show
    @equipment = Equipment.find(params[:id])
  end
  
  def edit
    @equipment = Equipment.find(params[:id])
  end
  
  def update
    equipment = Equipment.find(params[:id])
    equipment.update!(equipment_params)
    lab_equipment_name = equipment.lab_equipment_name
    OperationHistory.create_log(current_user.id, lab_equipment_name, 1)
    redirect_to equipment
  end
  
  def destroy
    equipment = Equipment.find(params[:id])
    lab_equipment_name = equipment.lab_equipment_name
    OperationHistory.create_log(current_user.id, lab_equipment_name, 2)
    equipment.destroy!
    redirect_to root_path
  end

  private

  def equipment_params
    params.require(:equipment).permit(
      :genre, 
      :lab_equipment_name, 
      :maker_name, 
      :product_name, 
      :purchase_year, 
      :asset_num, 
      :price, 
      :lendings_status, 
      :disposal_status, 
      :remarks)
  end

  def send_equipments_csv(equipments)
    csv_data = CSV.generate do |csv|
      column_names = %w(備品ジャンル 研究室用備品名 メーカー名 製品名 購入年度 資産番号 値段 備考 データ追加日 データ追加者)
      csv << column_names
      equipments.each do |equipment|
        column_values = [
          equipment.genre,
          equipment.lab_equipment_name,
          equipment.maker_name,
          equipment.product_name,
          equipment.purchase_year,
          equipment.asset_num,
          equipment.price,
          equipment.remarks,
          equipment.created_at,
          equipment.user.user_name
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "備品一覧.csv")
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Equipment.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end


end

app/helpers/equipments_helper.rb
module EquipmentsHelper
  def sort_order(column, title)
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"

    link_to title, { sort: column, direction: direction }
  end
end

app/views/equipments/edit.html.erb
<p>備品データの編集</p>
<%= form_with model: @equipment, url: equipment_path, method: :patch, local: true do |f| %>
  <p>備品ジャンル：<%= f.text_field :genre %></p>
  <p>研究室用備品名：<%= f.text_field :lab_equipment_name %></p>
  <p>メーカー名：<%= f.text_field :maker_name %></p>
  <p>製品名：<%= f.text_field :product_name %></p>
  <p>購入年度：<%= f.text_field :purchase_year %></p>
  <p>資産番号：<%= f.text_field :asset_num %></p>
  <p>金額：<%= f.text_field :price %></p>
  <p>備考：<%= f.text_field :remarks %></p>
  <%= f.submit "更新" %>
<% end %>

app/views/equipments/index.html.erb
<h1>Equipments#index</h1>

<% if current_user.admin? %>
  <p>備品データの追加</p>
  <%= form_with model: @equipment, url: equipments_path, method: :post, local: true do |f| %>
  <div>
    <%= f.label :genre %>
    <%= f.select :genre, Equipment.genres_i18n.invert %>
  </div>
    <p>研究室用備品名：<%= f.text_field :lab_equipment_name %></p>
    <p>メーカー名：<%= f.text_field :maker_name %></p>
    <p>製品名：<%= f.text_field :product_name %></p>
    <p>購入年度：<%= f.text_field :purchase_year %></p>
    <p>資産番号：<%= f.text_field :asset_num %></p>
    <p>金額：<%= f.text_field :price %></p>
    <p>備考：<%= f.text_field :remarks %></p>
    <%= f.submit "送信" %>
  <% end %>
<% else %>
<% end %>

<p>備品データ一覧</p>
<%= paginate @equipments %>

<%= search_form_for @q, url: equipments_path do |f| %>
  <%= f.label :genre_eq, "備品ジャンル" %>
  <%= f.search_field :genre_eq %>
  <%= f.label :purchase_year_eq, "購入年" %>
  <%= f.search_field :purchase_year_eq %>
  <%= f.label :lab_equipment_name_or_maker_name_or_asset_num_cont, "それ以外の項目で検索" %>
  <%= f.search_field :lab_equipment_name_or_maker_name_or_asset_num_cont %>
  <%= f.submit "検索" %>
<% end %>

<% if current_user.admin? %>
<%= link_to "CSVエクスポート",equipments_path(format: :csv) %>
<% else %>
<% end %>

<table border="1">
  <thead>
    <tr>

      <th scope="col"><%= sort_order "id", "id" %></th>
      <th scope="col"><%= sort_order "genre", "備品ジャンル" %></th>
      <th scope="col"><%= sort_order "lab_equipment_name", "研究室用備品名" %></th>
      <th scope="col"><%= sort_order "maker_name", "メーカー名" %></th>
      <th scope="col"><%= sort_order "product_name", "製品名" %></th>
      <th scope="col"><%= sort_order "purchase_year", "購入年度" %></th>
      <th scope="col"><%= sort_order "asset_num", "資産番号" %></th>
      <th scope="col">ステータス</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @equipments.each.with_index(1) do |equipment, i| %>
      <tr>
        <th><%= equipment.id %></th>
        <td><%= equipment.genre_i18n %></td>
        <td><%= equipment.lab_equipment_name %></td>
        <td><%= equipment.maker_name %></td>
        <td><%= equipment.product_name %></td>
        <td><%= equipment.purchase_year %></td>
        <td><%= equipment.asset_num %></td>
        <td>
          <% if equipment.lendings_status == 0 %>
            返却済
          <% elsif equipment.lendings_status == 1 %>
            貸出中
          <% end %>
          /
          <% if equipment.disposal_status == 0 %>
            未廃棄
          <% elsif equipment.disposal_status == 1 %>
            廃棄済
          <% end %>
          <%=  %>
        </td>
        <td>
        <% if current_user.admin? %>
          <%= link_to "詳細", equipment %>
          <%= link_to "編集", edit_equipment_path(equipment) %>
        <% else %>
          <%= link_to "詳細", equipment %>
        <% end %>
          <% if equipment.lendings_status == 0 %>
            <%= link_to "貸出", {controller: "lendings", action: "lending", id: equipment.id}, method: :post %>
          <% elsif equipment.lendings_status == 1 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/equipments/show.html.erb
<h1>備品データ詳細</h1>
<p> 備品ジャンル:<%= @equipment.genre %></p>
<p> 研究室用備品名:<%= @equipment.lab_equipment_name %></p>
<p> メーカー名:<%= @equipment.maker_name %></p>
<p> 製品名:<%= @equipment.product_name %></p>
<p> 購入年度:<%= @equipment.purchase_year %></p>
<p> 資産番号:<%= @equipment.asset_num %></p>
<p> 値段:<%= @equipment.price %></p>

<% if @equipment.disposal_status == 0 %>
<p>未廃棄</p>
<% elsif @equipment.disposal_status == 1 %>
<p>廃棄済み</p>
<% end %>

<p> 備考:<%= @equipment.remarks %></p>
<p> データ作成者:<%= @equipment.user.user_name %>（<%= @equipment.user.last_name %><%= @equipment.user.first_name %>）</p>
<p> データ作成日時:<%= @equipment.created_at %></p>
<p> データ更新日時:<%= @equipment.updated_at %></p>

<% if current_user.admin? %>
<%= link_to "編集", edit_equipment_path(@equipment) %>
<%= link_to "削除", @equipment, method: :delete, data: { confirm: "削除しますか?" } %>
<% else %>
<% end %>